# Generated by Django 5.1.2 on 2024-11-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=30)),
                ('original_platform', models.CharField(choices=[('PlayStation 1', 'Ps1'), ('PlayStation 2', 'Ps2'), ('PlayStation 3', 'Ps3'), ('PlayStation 4', 'Ps4'), ('PlayStation 5', 'Ps5'), ('Steam', 'Pc')], default='Steam', max_length=13)),
                ('remastered_platform', models.CharField(blank=True, choices=[('PlayStation 1', 'Ps1'), ('PlayStation 2', 'Ps2'), ('PlayStation 3', 'Ps3'), ('PlayStation 4', 'Ps4'), ('PlayStation 5', 'Ps5'), ('Steam', 'Pc')], default='null', max_length=13, null=True)),
                ('playing_status', models.CharField(choices=[('Backlogged', 'Back'), ('Playing', 'Play'), ('Finished', 'Done')], default='Playing', max_length=15)),
                ('completion_status', models.CharField(choices=[('Storyline', 'Story'), ('Trophy Hunting', 'Trophy'), ('Achieving 100%', 'Beyond'), ('Completed', 'Complete')], default='Storyline', max_length=15)),
                ('platinum', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('hours_played', models.IntegerField()),
            ],
        ),
    ]
