# Generated by Django 5.1.2 on 2024-11-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_image_path',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/'),
        ),
    ]
