# Generated by Django 5.1.2 on 2024-11-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_game_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='single_player',
            field=models.BooleanField(default=True),
        ),
    ]
